[pytest]
# Папка с selenium тестами
testpaths = tests_selenium

# Подробный вывод + короткий traceback
addopts = -v --tb=short

# Маркеры
markers =
    smoke: Critical UI tests
    slow: Tests that take more time
